name: "${project.name}"
version: ${project.version}
main: "${project.main}"
api-version: ${project.api.version}
author: "${project.author}"
website: "${project.url}"
description: "${project.description}"
depend: [${dependencies}]
softdepend: [${soft-dependencies}]
