#========================================
# ${project.name} ${project.version}
#   - config.yml
#========================================

# whether check update or not
checkUpdate: true

# and a string value
message: Hello World and Welcome! :)

# and list of string
team:
  rules:
    - Play Nice
    - Respect others
    - Have Fun
    - Dont swear

storage:
  type: ${storage.type}
  mysql:
    host: ${storage.mysql.host}
    port: ${storage.mysql.port}
    user: ${storage.mysql.user}
    password: ${storage.mysql.password}
    db_name: ${storage.mysql.db_name}
    table_prefix: ${storage.mysql.table_prefix}
    conn_timeout_ms: ${storage.mysql.conn_timeout_ms}
    max_conns: ${storage.mysql.max_conns}
    max_lifetime_ms: ${storage.mysql.max_lifetime_ms}
    use_ssl: ${storage.mysql.use_ssl}

#__END__
